# -*- coding: utf-8 -*-
"""face_mask_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zh3Iw-p_jYn_8DgLtQgxZmDFf62MxWfR
"""

!pip install kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d omkargurav/face-mask-dataset

import os
import zipfile
zip_path = '/content/face-mask-dataset.zip'
data_path = '/content/dataset'

if not os.path.exists(data_path):
  os.makedirs(data_path)

with zipfile.ZipFile(zip_path, 'r') as fille:
  fille.extractall(data_path)
  print("Dataset extracted...")

!ls

#importing the dependencies

!pip install opencv-python-headless

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
from sklearn.model_selection import train_test_split

with_mask_path = '/content/dataset/data/with_mask/'
without_mask_path = '/content/dataset/data/without_mask/'

mask_img_file = os.listdir(with_mask_path)
no_mask_img_file = os.listdir(without_mask_path)

print(mask_img_file[0:5])

print(no_mask_img_file[0:5])

print(f"No. of with mask image : {len(mask_img_file)}")
print(f"No. of without mask image : {len(no_mask_img_file)}")

#creating label for the images from two class
# with mask --> 1
# without mask --> 0

mask_label = [1]* len(mask_img_file)
no_mask_label = [0] * len(no_mask_img_file)

print(no_mask_label[0:5])
print(mask_label[:5])

labels = mask_label + no_mask_label
print(len(labels))
print(labels[:5])
print(labels[-5:])

#Displaying the images

img = mpimg.imread('/content/dataset/data/with_mask/with_mask_2634.jpg')
plt.imshow(img)

img = mpimg.imread('/content/dataset/data/without_mask/without_mask_2733.jpg')
plt.imshow(img)

# Image Processing
# 1. Resize the images
# 2. Convert to NumPy arrays

import tensorflow as tf
import os

full_path = '/content/full_data/'

if not os.path.exists(full_path):
  os.makedirs(full_path)

train_ds = tf.keras.utils.image_dataset_from_directory(
    '/content/dataset/data',
    validation_split = 0.25,
    label_mode = 'binary',
    subset = 'training',
    image_size = (150,150),
    batch_size = 32,
    seed = 133
)


test_ds = tf.keras.utils.image_dataset_from_directory(
    '/content/dataset/data',
    validation_split = 0.25,
    label_mode = 'binary',
    subset = 'validation',
    image_size = (150,150),
    batch_size = 32,
    seed = 133
)

def normalize(image, label):
  image = tf.cast(image, tf.float32) / 255.0
  return image, label

train_ds = train_ds.map(normalize)
test_ds = test_ds.map(normalize)

train_ds.save('/content/full_data/train')
test_ds.save('/content/full_data/test')

tain_ds = tf.data.Dataset.load('/content/full_data/train')
test_ds = tf.data.Dataset.load('/content/full_data/test')

for images, labels in train_ds.take(1):

    print(labels.numpy())

    plt.figure(figsize=(10, 5))
    for i in range(4):
        ax = plt.subplot(1, 4, i + 1)
        plt.imshow(images[i].numpy())
        plt.title(f"Label: {int(labels[i])}")
        plt.axis("off")
    plt.show()
    break

# train_ds and test_ds are redy to be fed to the cnn.

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape = (150,150,3)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation= 'relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(128, activation = 'relu'),
    layers.Dropout(0.5),

    layers.Dense(8, activation= 'relu'),

    layers.Dense(1, activation= 'sigmoid')
])

model.summary()



model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

earlystopping = EarlyStopping(
    monitor = 'val_loss',
    patience = 5,
    restore_best_weights = True
)

model_check_point = ModelCheckpoint(
    'mask_detection_model.keras',
    monitor = 'val_loss',
    save_best_only = True,
    mode = 'min'
)

history = model.fit(train_ds, validation_data = test_ds, epochs = 10, verbose=1, callbacks = [earlystopping, model_check_point])

loss, accuraccy =  model.evaluate(test_ds)

print(f"Accuracy :: {accuraccy*100:.2f}")
print("Loss :: ", loss)

histt= history.history

plt.plot(histt['accuracy'], label = "Training Accuracy")
plt.plot(histt['val_accuracy'], label = "Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

plt.plot(histt['loss'], label = 'Training Loss')
plt.plot(histt['val_loss'], label = 'Validation Loss')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

from tensorflow.keras.preprocessing import image

def predict_image(image_path):
  img = Image.open(image_path).convert('RGB')
  img = img.resize((150,150))
  img = np.array(img) / 255.0
  img_batch = np.expand_dims(img, axis = 0)

  prediction = model.predict(img_batch)

  probability = prediction[0][0]

  if(probability > 0.5):
    print("NO MASK")
  else:
    print("MASK")

  plt.imshow(img)
  plt.axis('off')
  plt.show()

img_list = []

# img_list.append('/content/cannes-france-aishwarya-rai-attends-the-la-venue-de-lavenir-red-carpet-at-the-78th-annual.webp')
img_list.append('/content/pexels-photo-3571628.webp')
img_list.append('/content/portrait-of-young-woman-putting-on-a-protective-mask.webp')
img_list.append('/content/woman-in-a-surgical-mask.webp')
# img_list.append('/content/wp3983425.webp')
# img_list.append('/content/WhatsApp Image 2025-12-06 at 02.43.59_11c49f06.jpg')
# img_list.append('/content/bollywood-actress-sushmita-sen-attends-a-fashion-show-by-designer-vikram-phadnis-in-mumbai-on.webp')
img_list.append('/content/240_F_1567621131_O80tkKHBQjGruFg9jG49kbH0lzP7CAVf.jpg')

for image_path in img_list:
  predict_image(image_path)

mask_counts = len(os.listdir('/content/dataset/data/with_mask'))
no_mask_counts = len(os.listdir('/content/dataset/data/without_mask'))

print(f"Mask images : {mask_counts}")
print(f"No mask images : {no_mask_counts}")

